### ISSUE TITLE
I have created an iOS client for Status

### ISSUE THREAD

**Issue by JGeek00** [dani3l0/Status#10]
I have developed Server Status, a client for iPhone and iPad for this service. It's available for free on the [AppStore](https://apps.apple.com/us/app/server-status-server-monitor/id6479648296).

**Comment by dani3l0** [comment]
Wow, looks wonderful! I love apps written in Flutter with simple layouts like this. I have no iOS devices, but I'm waiting for Android release, would be great to have such handy tool on mobile phone

**Comment by JGeek00** [comment]
Well, this app is not written using Flutter, it's written on Swift and SwiftUI. That's the reason why I cannot compile it for Android, but maybe on the future I consider developing an Android native version. But for that first I need to learn Android development 😂

**Comment by dani3l0** [comment]
> But for that first I need to learn Android development 😂

if you don't want to curse and get angry all the time, just stay off from native Android development :laughing:. On each OS version most APIs are incompatible, work differently or they are just 'deprecated'. Documentation often is very hard to read and online tutorials usually don't work.
Sounds like rant a bit, but that's just my experience :rofl: 

Anyways, I'll mention your iOS app in README file, so more people might check it out.
Thanks for your contribution!

**Comment by JGeek00** [comment]
🙁 that doesn't look good. Well, will see on the future what I can do. For now I'm happy with iOS development with SwiftUI. Thank you for adding my application.
