### ISSUE TITLE
Display the device name in the title when you have multi machines?

### ISSUE THREAD

**Issue by cooocy** [dani3l0/Status#2]
I like this simple and elegant style! Thanks!!
Because I have multiple devices, do you think it will be more friendly if the name of the device is displayed in the title? Just like this:
<img width="649" alt="image" src="https://github.com/dani3l0/Status/assets/26477692/dca6d629-7938-42f8-a16e-1298c9f6c76f">

**Comment by dani3l0** [comment]
Hey, thanks for checking out my project and opening this issue.
No problem, the feature you requested will be added as soon as I add planned 'Settings' section with some customizable stuff. There will be a possibility to easily enable/disable it.
I'm kinda busy right now and don't have much spare time for coding, but I think changes still can be done this week.
