### ISSUE TITLE
Support 'go back' and 'go forward' of browser?

### ISSUE THREAD

**Issue by cooocy** [dani3l0/Status#3]
Now it doesn't support 'go back' and 'go forward' of browser or 'left slide' and 'right slide' of cell phone. When I want to go back, I must click the back icon on left of the title.
If it can support the above functions, I think it will be more friendly to users.

**Comment by dani3l0** [comment]
That's a good idea, would greatly improve user experience.
By briefly looking at JS files, I guess we need to somehow integrate `window.history` with [this function](https://github.com/dani3l0/Status/blob/main/html/js/main.js#L30) and... that should do the trick.

**Comment by cooocy** [comment]
I have synced your commits to my forked repository and run successfully, it's cool!
