### ISSUE TITLE
Will there be the ability to add multiple hosts?

### ISSUE THREAD

**Issue by scharez** [dani3l0/Status#5]
Hi, nice monitoring tool.

Will there be the ability to add more hosts for one webinterface

**Comment by dani3l0** [comment]
**Short answer: no.**

**Long answer:** Adding more features to front-end would require creating more files, which heavily affects site load time (especially on slower networks). Using tools like JS minifiers will make app installation harder and requires more tools to be installer.

**Hovewer:** I'm planning to rewrite Status in `Go`, and front-end with help of `Vite`. With `Go` I will be able to provide all-in-one, optimized single-binary file which has no dependencies making installation waaay easier. `Vite` would optimize the front-end making it faster and allowing me to pack more features.

Ofc, I will keep multiple hosts feature in mind. Thanks for opening the issue!
