### ISSUE TITLE
Feel free to use our instance as a demo!

### ISSUE THREAD

**Issue by Codixer** [dani3l0/Status#6]
Post/advertisement: https://enshittification.social/@Enshittification/111139849324647092 

Our status page: https://status.enshittification.social/

**Comment by dani3l0** [comment]
Wow, awesome. I will be pleased to use your demo instead of Render one. Thanks for choosing this project and thanks for sharing!

Btw, I see connection speed marked as -1000Kbit/s, what sandboxing technology do u use to reproduce this bug?

**Comment by Codixer** [comment]
> Btw, I see connection speed marked as -1000Kbit/s, what sandboxing technology do u use to reproduce this bug?
I don't use a sandbox, it's hosted as a service directly. (So running the python file on the system directly)

**Comment by dani3l0** [comment]
> https://hetzner.com/

I guess they use some network config that does not provide `/sys/class/net/{interface}/speed` file, but it can be easily fixed in front-end by one JS line

Anyways, this evening or tomorrow afternoon I'm gonna fix the above and put your instance url in READMEs as a default demo, thanks again!

**Comment by JGeek00** [comment]
Just for your information. The demo page is down.

**Comment by Codixer** [comment]
Heya @dani3l0, somehow I was just notified about this post. (For some reason???). I closed down enshittification, sorry.

**Comment by dani3l0** [comment]
Very sad :((((

We'll then switch to Render for a while
