### ISSUE TITLE
How connect domain

### ISSUE THREAD

**Issue by amirlime** [dani3l0/Status#7]
How connect domain

**Comment by amirlime** [comment]
how to connect domain to status
![image](https://github.com/dani3l0/Status/assets/122648967/13d26b39-9a14-463c-9391-50e3b8e5776e)

**Comment by dani3l0** [comment]
Okay, that's still very little information, but I can give you a hand

1. You need to have a public IP address and your machine has to be accessible outside your local network
2. You can buy a domain or use [noip.com](noip.com) to link your IP with some domain name, if you have no public IP you can try using Ngrok
3. To assign domain/subdomain for Status, you will need to use a reverse proxy (like Nginx or Caddy)
